CREATE TABLE contracts (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  property_id uuid NOT NULL REFERENCES properties(id) ON DELETE RESTRICT,
  tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE RESTRICT,
  start_date date NOT NULL,
  end_date date NOT NULL,
  currency currency_type NOT NULL DEFAULT 'ARS',
  base_rent numeric NOT NULL,
  current_rent numeric NOT NULL,
  payment_day integer NOT NULL CHECK (payment_day BETWEEN 1 AND 31),
  legal_framework legal_framework NOT NULL DEFAULT 'dnu_70_2023',
  agency_collects boolean NOT NULL DEFAULT true,
  commission_percentage numeric NOT NULL DEFAULT 0,
  late_fee_enabled boolean NOT NULL DEFAULT false,
  late_fee_type late_fee_type,
  late_fee_value numeric,
  status contract_status NOT NULL DEFAULT 'activo',
  notes text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT valid_dates CHECK (end_date > start_date),
  CONSTRAINT valid_rent CHECK (base_rent > 0 AND current_rent > 0),
  CONSTRAINT valid_commission CHECK (commission_percentage >= 0 AND commission_percentage <= 100)
);
